### ISSUE TITLE
AOT without dependencies

### ISSUE THREAD

**Issue by Immortalin** [yoshiquest/forge-clj#9] opened 2015-11-21 02:56 UTC
Is it possible to compile the libraries together into the mod so that users no longer have to install them separately?

**Comment by ryanhaney97** [comment] 2015-11-21 04:28
Well, yes it is. However, forge-clj is separate for a reason. Because if you had more than one mod using forge-clj, then forge-clj would have to be loaded multiple times, and would have to use multiple copies of the same thing.

You COULD shade forge-clj into the installation (I did this with clojure.jar so that you don't have to include that in your mods folder), but I wouldn't recommend it due to forge-clj's size. However, this is not something I plan on supporting.

**Comment by Immortalin** [comment] 2015-11-21 05:38
Maybe add a section add the bottom of the README?

**Comment by Immortalin** [comment] 2015-11-21 05:39
I am worried about dependency hell if this gets popular

**Comment by ryanhaney97** [comment] 2015-12-03 19:01
I understand your problems with dependency hell, but the problem is that forge-clj also includes Clojure itself, so I really would just recommend using this as an additional api to be installed. Either way, there are plenty of other mods that do this already (having their own api installed separately I mean), so this really shouldn't be that much of a problem.

I'll still keep this open though, since one thing I need to get around to is removing tools.nrepl from the shade in forge-clj, so I'll use this for that related issue.

**Comment by ryanhaney97** [comment] 2016-06-13 20:33
Removed tools.nrepl as of Version 0.6.0. I SHOULD have just created a new issue for that, but whatever, closing this now.

**Closed as completed by ryanhaney97** 2016-06-13 20:33 UTC
